Repository playcanvas/pcui, pull requests merged in 2020-12, with the labels that each got.

#44 Fix references in the data binding docs
  README.md
  docs/pages/data-binding/observer.markdown
  src/examples/Observer/index.stories.jsx
Labels: bug, documentation

#46 ContextMenu trigger element
  src/components/ContextMenu/index.js
Labels: enhancement

#35 fix the handle position
  src/components/SliderInput/index.js
Labels: bug

#48 Document the pcui site build process
  docs/README.md
  docs/_config.yml
  docs/_config_local.yml
  docs/create-component-pages.js
  docs/pages/4-components/ContextMenu.markdown
  package.json
Labels: documentation

#49 Expose the TreeView component
  src/components/TreeView/index.js
  src/components/TreeView/index.stories.jsx
  src/components/TreeViewItem/index.js
  src/components/index.js
  src/index.js
Labels: bug, enhancement

#50 Resizable TextAreaInput component
  src/components/TextAreaInput/index.js
  src/components/TextAreaInput/style.scss
  src/components/TextInput/style.scss
Labels: enhancement

#51 Expose the ArrayInput component
  src/components/ArrayInput/component.jsx
  src/components/ArrayInput/index.js
  src/components/ArrayInput/index.stories.jsx
  src/components/ArrayInput/style.scss
  src/components/VectorInput/index.js
  src/components/index.js
  src/index.js
Labels: enhancement

#56 Export the TreeView class
  src/index.js
Labels: bug

#57 SliderInput handle position fix
  src/components/SliderInput/index.js
Labels: bug

#55 Fix the TextInput component text alignment
  src/components/TextAreaInput/style.scss
  src/components/TextInput/style.scss
Labels: bug

#59 TreeView component story typo
  src/components/TreeView/index.stories.jsx
Labels: documentation

#61 [TreeView] rename item font style update
  src/components/TreeView/style.scss
Labels: bug

#65 History combine fixes
  src/components/NumericInput/index.js
  src/components/SliderInput/index.js
Labels: bug

#66 Change slider handle behaviour
  package.json
  src/components/SliderInput/index.js
Labels: bug

#67 Docs update
  docs/create-component-pages.js
  docs/pages/4-components/ArrayInput.markdown
  docs/pages/4-components/TreeView.markdown
Labels: documentation
