Repository playcanvas/pcui, pull requests merged in 2020-10, with the labels that each got.

#9 triv: fixes a 404
  docs/pages/2-react.markdown
Labels: bug

#10 Updates to the docs & storybook
  .storybook/main.js
  .storybook/utils/docscript.js
  docs/Gemfile.lock
  docs/_config.yml
  docs/_config_local.yml
  docs/index.markdown
  src/scss/pcui-storybook.scss
Labels: bug, enhancement

#13 fix typo in Progress component description
  src/components/Progress/index.js
  yarn.lock
Labels: bug, documentation

#15 Hide slider on read only numeric input
  src/components/NumericInput/style.scss
Labels: bug

#18 Fix selectable labels to allow text selection
  src/components/Label/style.scss
Labels: bug

#19 Fix error when dragging numeric input that has no slider, Fix garbage…
  src/components/NumericInput/index.js
Labels: bug

#25 Add shadow to context menu
  package-lock.json
  src/components/ContextMenu/style.scss
Labels: enhancement

#29 Expose the ContextMenu component
  src/components/index.js
  src/index.js
Labels: enhancement
