Repository playcanvas/pcui, pull requests merged in 2022-12, with the labels that each got.

#192 React panel rendering fix
  src/components/Element/component.tsx
  src/components/Panel/component.tsx
Labels: bug

#194 SelectInput: remove createLabelText default value
  src/components/SelectInput/index.ts
Labels: bug

#196 Remove JSDoc and WebPack NPM dependencies
  package-lock.json
  package.json
Labels: enhancement

#197 Remove four NPM dependencies
  package-lock.json
  package.json
Labels: enhancement

#199 Update NPM dependencies
  package-lock.json
  package.json
  rollup.config.mjs
Labels: enhancement

#201 Enable Stylelint to lint SCSS files
  .github/workflows/ci.yml
  .stylelintrc.json
  package-lock.json
  package.json
  src/components/ArrayInput/style.scss
  src/components/BooleanInput/style.scss
  src/components/Button/style.scss
  src/components/Canvas/style.scss
  src/components/ColorPicker/style.scss
  src/components/Container/style.scss
  src/components/Element/style.scss
  src/components/GradientPicker/style.scss
  src/components/GridViewItem/style.scss
  src/components/InfoBox/style.scss
  src/components/Label/style.scss
  src/components/MenuItem/style.scss
  src/components/NumericInput/style.scss
  src/components/Overlay/style.scss
  src/components/Panel/style.scss
  src/components/Progress/style.scss
  src/components/RadioButton/style.scss
  src/components/SelectInput/style.scss
  src/components/SliderInput/style.scss
  src/components/TextInput/style.scss
  src/components/TreeView/style.scss
  src/examples/BidirectionalBinding/style.scss
  src/examples/Observer/style.scss
  src/examples/TodoList/style.scss
  src/scss/_pcui-common.scss
  src/scss/components.scss
  src/scss/font-icon.scss
  src/scss/fonts-storybook.scss
  src/scss/fonts.scss
  src/scss/fonts/PlayIcons-Regular-woff.scss
  src/scss/fonts/buildFontIcons.js
  src/scss/pcui-base.scss
  src/scss/pcui-storybook.scss
  src/scss/themes/green/colors.scss
  src/scss/themes/green/style.scss
  src/scss/themes/grey/colors.scss
  src/scss/themes/grey/style.scss
  src/scss/variables.scss
Labels: enhancement

#205 Menu component changes
  src/components/Menu/index.ts
  src/components/MenuItem/index.ts
Labels: enhancement

#206 MenuItem select event
  src/components/MenuItem/index.ts
Labels: enhancement

#210 Remove `Canvas#dom`
  src/components/Canvas/index.ts
  src/components/GradientPicker/index.ts
Labels: enhancement

#211 Remove redundant `Canvas` args
  src/components/Canvas/index.ts
Labels: bug

#208 Retire `Element#element` and `Element#disabled`
  src/components/ColorPicker/index.ts
  src/components/GradientPicker/index.ts
  src/components/MenuItem/index.ts
  src/components/Panel/index.ts
Labels: enhancement

#209 Migrate key event handlers to use `key` instead of `keyCode`
  src/components/BooleanInput/index.ts
  src/components/Button/index.ts
  src/components/ColorPicker/index.ts
  src/components/GradientPicker/index.ts
  src/components/Menu/index.ts
  src/components/NumericInput/index.ts
  src/components/RadioButton/index.ts
  src/components/SelectInput/index.ts
  src/components/SliderInput/index.ts
  src/components/TextAreaInput/index.ts
  src/components/TextInput/index.ts
  src/components/TreeView/index.ts
Labels: enhancement

#212 Improve Element typing
  src/components/Element/index.ts
  src/components/GridView/index.ts
  src/components/GridViewItem/index.ts
  src/components/Menu/index.stories.tsx
  src/components/Menu/index.ts
  src/components/MenuItem/index.ts
  src/components/Overlay/index.ts
  src/components/SelectInput/index.ts
  src/components/SliderInput/index.ts
  src/components/TreeView/index.ts
  src/components/TreeViewItem/index.ts
Labels: enhancement

#215 Remove unused local storage API
  src/helpers/localStorage.ts
Labels: enhancement

#217 Remove some occurrences of 'as any'
  src/components/Container/index.ts
  src/components/TextInput/index.ts
Labels: enhancement

#216 Remove `conf-tsd.json`
  conf-tsd.json
Labels: enhancement

#214 Remove unused functions from `utils.ts`
  src/helpers/utils.ts
Labels: enhancement

#218 Remove `text` argument for `RadioButton`
  src/components/RadioButton/index.ts
Labels: bug

#219 Minor README improvements
  README.md
Labels: bug

#220 Added steps to build PCUI for the PlayCanvas Editor
  BUILDGUIDE.md
  README.md
Labels: documentation

#221 Further type refinements
  package.json
  src/Math/color-value.ts
  src/binding/BindingBase/index.ts
  src/binding/BindingElementToObservers/index.ts
  src/binding/BindingObserversToElement/index.ts
  src/binding/BindingTwoWay/index.ts
  src/class.ts
  src/components/ArrayInput/index.ts
  src/components/BooleanInput/index.ts
  src/components/Button/index.ts
  src/components/Canvas/index.ts
  src/components/Code/index.ts
  src/components/ColorPicker/index.ts
  src/components/Container/index.ts
  src/components/Divider/index.ts
  src/components/Element/component.tsx
  src/components/Element/index.ts
  src/components/GradientPicker/component.tsx
  src/components/GradientPicker/index.ts
  src/components/GridView/index.ts
  src/components/GridViewItem/component.tsx
  src/components/GridViewItem/index.ts
  src/components/InfoBox/index.ts
  src/components/Input/index.ts
  src/components/Label/index.ts
  src/components/LabelGroup/component.tsx
  src/components/LabelGroup/index.ts
  src/components/Menu/index.ts
  src/components/MenuItem/index.ts
  src/components/NumericInput/index.ts
  src/components/Overlay/index.ts
  src/components/Panel/component.tsx
  src/components/Panel/index.ts
  src/components/Progress/index.ts
  src/components/RadioButton/index.ts
  src/components/SelectInput/index.ts
  src/components/SliderInput/component.tsx
  src/components/SliderInput/index.ts
  src/components/Spinner/component.tsx
  src/components/Spinner/index.ts
  src/components/TextAreaInput/component.tsx
  src/components/TextAreaInput/index.ts
  src/components/TextInput/index.ts
  src/components/TreeView/component.tsx
  src/components/TreeView/index.ts
  src/components/TreeViewItem/component.tsx
  src/components/TreeViewItem/index.ts
  src/components/VectorInput/component.tsx
  src/components/VectorInput/index.ts
  src/examples/BidirectionalBinding/index.stories.tsx
  src/examples/History/index.stories.tsx
  src/examples/Observer/index.stories.tsx
  src/examples/TodoList/index.stories.tsx
  src/helpers/search.ts
  src/helpers/utils.ts
Labels: enhancement

#222 Refactor DOM event handlers
  src/binding/BindingObserversToElement/index.ts
  src/components/ArrayInput/index.ts
  src/components/BooleanInput/index.ts
  src/components/Button/index.ts
  src/components/ColorPicker/index.ts
  src/components/Container/index.ts
  src/components/Element/index.ts
  src/components/GradientPicker/index.ts
  src/components/GridView/index.ts
  src/components/GridViewItem/index.ts
  src/components/Menu/index.ts
  src/components/MenuItem/index.ts
  src/components/NumericInput/index.ts
  src/components/Overlay/index.ts
  src/components/Panel/index.ts
  src/components/RadioButton/index.ts
  src/components/SelectInput/index.ts
  src/components/SliderInput/index.ts
  src/components/TextInput/index.ts
  src/components/TreeView/index.ts
  src/components/TreeViewItem/index.ts
  src/components/VectorInput/index.ts
Labels: enhancement

#227 Improve event docs
  src/components/ArrayInput/index.ts
  src/components/Container/index.ts
  src/components/Element/index.ts
  src/components/Panel/index.ts
  src/components/TreeView/index.ts
  src/components/TreeViewItem/index.ts
Labels: enhancement

#229 Remove CSS vendor prefixing
  .stylelintrc.json
  package-lock.json
  package.json
  rollup.config.mjs
  src/components/ColorPicker/style.scss
  src/components/Element/style.scss
  src/components/Panel/style.scss
  src/components/Progress/style.scss
  src/scss/_pcui-common.scss
Labels: enhancement
