Repository playcanvas/pcui, pull requests merged in 2023-01, with the labels that each got.

#230 More Stylelint fixes
  .stylelintrc.json
  src/components/Button/style.scss
  src/components/Canvas/style.scss
  src/components/ColorPicker/style.scss
  src/components/GridView/style.scss
  src/components/Label/style.scss
  src/components/LabelGroup/style.scss
  src/components/Overlay/style.scss
  src/components/Panel/style.scss
  src/components/Progress/style.scss
  src/components/SelectInput/style.scss
  src/components/SliderInput/style.scss
  src/components/TextAreaInput/style.scss
  src/components/TextInput/style.scss
  src/components/TreeView/style.scss
  src/scss/_pcui-common.scss
  src/scss/font-icon.scss
  src/scss/fonts-storybook.scss
  src/scss/fonts.scss
Labels: enhancement

#231 Minor fixes for Docs Site
  docs/pages/1-getting-started.markdown
  docs/pages/2-react.markdown
  docs/pages/3-data-binding.markdown
  docs/pages/6-storybook.markdown
  docs/pages/data-binding/observer.markdown
  docs/pages/data-binding/two-way-binding.markdown
Labels: bug

#225 Generate MDN links in Typedocs
  package-lock.json
  package.json
Labels: enhancement

#224 Fix `mouseover` handling of `TreeViewItem`s
  src/components/TreeView/index.ts
  src/components/TreeViewItem/index.ts
Labels: bug

#232 Refactor `VectorInput`
  src/components/VectorInput/index.ts
Labels: enhancement

#228 PCUI Examples
  examples/arrayinput.html
  examples/booleaninput.html
  examples/button.html
  examples/canvas.html
  examples/code.html
  examples/colorpicker.html
  examples/divider.html
  examples/gradientpicker.html
  examples/gridview.html
  examples/index.html
  examples/infobox.html
  examples/label.html
  examples/labelgroup.html
  examples/menu.html
  examples/numericinput.html
  examples/overlay.html
  examples/panel.html
  examples/progress.html
  examples/radiobutton.html
  examples/selectinput.html
  examples/sliderinput.html
  examples/spinner.html
  examples/textareainput.html
  examples/textinput.html
  examples/treeview.html
  examples/vectorinput.html
Labels: enhancement

#235 Fix `Button` font when adding to body element
  src/components/Button/style.scss
Labels: bug

#237 Improve `Menu#position` docs
  examples/overlay.html
  src/components/Menu/index.ts
Labels: enhancement

#238 Fix creating `ArrayInput` without options
  src/components/ArrayInput/index.ts
Labels: bug

#239 Explicitly declare CSS accessors on `Element`
  src/components/Element/index.ts
Labels: enhancement

#236 Refactor `SliderInput`
  src/components/SliderInput/index.ts
  src/components/TextInput/index.ts
  src/helpers/utils.ts
Labels: enhancement

#241 Fix wheel event handler warning for `NumericInput`
  src/components/NumericInput/index.ts
Labels: bug

#242 Remove empty objects from constructor calls
  src/components/GradientPicker/index.ts
  src/components/GridViewItem/index.ts
  src/components/MenuItem/index.ts
  src/examples/BidirectionalBinding/index.stories.tsx
  src/examples/Observer/index.stories.tsx
Labels: enhancement

#244 Allow menu items with no `onSelect` function
  src/components/MenuItem/index.ts
Labels: bug

#245 Correctly handle non-numeric values entered into NumericInput
  src/components/NumericInput/index.ts
  src/components/TextInput/index.ts
Labels: bug

#246 Typing of `ColorPicker` now complete
  src/components/ColorPicker/index.ts
Labels: enhancement

#249 Simplify test for array element equality
  src/components/BooleanInput/index.ts
  src/components/Label/index.ts
  src/components/NumericInput/index.ts
  src/components/RadioButton/index.ts
  src/components/TextInput/index.ts
Labels: enhancement

#250 Better typing for Element
  src/components/Element/index.ts
Labels: enhancement

#251 Lint import statements
  package-lock.json
  package.json
  src/components/Menu/index.ts
Labels: bug, enhancement

#254 Remove redundant /index from ts imports
  src/binding/BindingBase/index.ts
  src/components/BooleanInput/index.ts
  src/components/Button/index.ts
  src/components/Canvas/index.ts
  src/components/Code/index.ts
  src/components/ColorPicker/index.ts
  src/components/Container/index.ts
  src/components/Divider/index.ts
  src/components/GradientPicker/index.ts
  src/components/GridView/index.ts
  src/components/GridViewItem/index.ts
  src/components/InfoBox/index.ts
  src/components/Input/index.ts
  src/components/Label/index.ts
  src/components/LabelGroup/index.ts
  src/components/Menu/index.ts
  src/components/NumericInput/index.ts
  src/components/Overlay/index.ts
  src/components/Panel/index.ts
  src/components/Progress/index.ts
  src/components/RadioButton/index.ts
  src/components/SelectInput/index.ts
  src/components/SliderInput/index.ts
  src/components/Spinner/index.ts
  src/components/TextAreaInput/index.ts
  src/components/TextInput/index.ts
  src/components/TreeView/index.ts
  src/components/TreeViewItem/index.ts
  src/components/VectorInput/index.ts
  src/components/index.ts
  src/index.ts
Labels: enhancement

#256 VectorInput default precision value
  src/components/VectorInput/index.ts
Labels: bug

#257 @playcanvas/observer as a dependency
  README.md
  docs/pages/1-getting-started.markdown
  package-lock.json
  package.json
Labels: documentation, dependencies

#264 Move icon font processing out of src folder
  .stylelintrc.json
  package.json
  src/scss/font-icon.scss
  src/scss/fonts/PlayIcons-Regular-woff.scss
  src/scss/fonts/_playicons-regular.scss
  src/scss/fonts/buildFontIcons.js
  utils/PlayIcons-Regular.woff
  utils/build-font-icons.mjs
Labels: enhancement

#263 Improve description and add keywords in package.json
  package.json
Labels: enhancement

#267 Remove _optionValue from Label
  src/components/Label/index.ts
  src/components/SelectInput/index.ts
Labels: enhancement

#269 Use modern notation for CSS color functions
  .stylelintrc.json
  src/components/ColorPicker/style.scss
  src/components/GradientPicker/style.scss
  src/components/MenuItem/style.scss
  src/components/Overlay/style.scss
  src/scss/themes/green/colors.scss
  src/scss/themes/grey/colors.scss
Labels: enhancement

#271 React LabelGroup linking fix
  src/components/LabelGroup/component.tsx
Labels: bug

#278 [FIX] Arrow keys to edit NumericInput value
  src/components/NumericInput/index.ts
Labels: bug

#276 Type `searchItems` function
  src/components/TreeView/index.ts
  src/components/TreeViewItem/index.ts
  src/helpers/search.ts
Labels: enhancement

#272 [BREAKING] Remove `Element#class` setter
  src/components/Element/index.ts
Labels: bug

#273 [BREAKING] Remove first parameter of `Element` constructor
  src/components/ArrayInput/index.ts
  src/components/BooleanInput/index.ts
  src/components/Button/index.ts
  src/components/Canvas/index.ts
  src/components/Code/index.ts
  src/components/ColorPicker/index.ts
  src/components/Container/index.ts
  src/components/Divider/index.ts
  src/components/Element/index.ts
  src/components/GradientPicker/index.ts
  src/components/GridView/index.ts
  src/components/GridViewItem/index.ts
  src/components/InfoBox/index.ts
  src/components/Label/index.ts
  src/components/LabelGroup/index.ts
  src/components/Menu/index.ts
  src/components/MenuItem/index.ts
  src/components/NumericInput/index.ts
  src/components/Overlay/index.ts
  src/components/Panel/index.ts
  src/components/Progress/index.ts
  src/components/RadioButton/index.ts
  src/components/SelectInput/index.ts
  src/components/SliderInput/index.ts
  src/components/Spinner/index.ts
  src/components/TextAreaInput/index.ts
  src/components/TextInput/index.ts
  src/components/TreeView/index.ts
  src/components/TreeViewItem/index.ts
  src/components/VectorInput/index.ts
Labels: enhancement

#274 [BREAKING] Remove `Element#classAdd` and `Element#classRemove`
  src/components/Container/index.ts
  src/components/Element/index.ts
  src/components/GridViewItem/index.ts
  src/components/Panel/index.ts
  src/components/TreeViewItem/index.ts
Labels: enhancement

#275 Move property initialization out of constructors
  src/components/ArrayInput/index.ts
  src/components/Canvas/index.ts
  src/components/Code/index.ts
  src/components/ColorPicker/index.ts
  src/components/Container/index.ts
  src/components/Element/index.ts
  src/components/MenuItem/index.ts
  src/components/Panel/index.ts
  src/components/SelectInput/index.ts
  src/components/TreeView/index.ts
  src/components/TreeViewItem/index.ts
Labels: enhancement

#279 NumericInput step default value
  src/components/NumericInput/index.ts
Labels: bug

#280 Remove defaults for the SliderInput's min / max arguments
  src/components/SliderInput/index.ts
Labels: bug

#282 Remove: flag allowSyntheticDefaultImports from ts config
  README.md
  docs/pages/2-react.markdown
  react/tsconfig.json
  src/components/ArrayInput/index.stories.tsx
  src/components/BooleanInput/index.stories.tsx
  src/components/Button/component.tsx
  src/components/Button/index.stories.tsx
  src/components/Canvas/component.tsx
  src/components/Canvas/index.stories.tsx
  src/components/Code/index.stories.tsx
  src/components/ColorPicker/component.tsx
  src/components/ColorPicker/index.stories.tsx
  src/components/Container/component.tsx
  src/components/Container/index.stories.tsx
  src/components/Divider/index.stories.tsx
  src/components/Element/component.tsx
  src/components/Element/index.ts
  src/components/GradientPicker/component.tsx
  src/components/GradientPicker/index.stories.tsx
  src/components/GridView/component.tsx
  src/components/GridView/index.stories.tsx
  src/components/InfoBox/component.tsx
  src/components/InfoBox/index.stories.tsx
  src/components/Label/component.tsx
  src/components/Label/index.stories.tsx
  src/components/LabelGroup/index.stories.tsx
  src/components/Menu/component.tsx
  src/components/Menu/index.stories.tsx
  src/components/NumericInput/index.stories.tsx
  src/components/Overlay/index.stories.tsx
  src/components/Panel/component.tsx
  src/components/Panel/index.stories.tsx
  src/components/Progress/index.stories.tsx
  src/components/RadioButton/index.stories.tsx
  src/components/SelectInput/index.stories.tsx
  src/components/SliderInput/index.stories.tsx
  src/components/Spinner/component.tsx
  src/components/Spinner/index.stories.tsx
  src/components/TextAreaInput/index.stories.tsx
  src/components/TextInput/index.stories.tsx
  src/components/TreeView/component.tsx
  src/components/TreeView/index.stories.tsx
  src/components/VectorInput/index.stories.tsx
  src/examples/BidirectionalBinding/index.stories.tsx
  src/examples/Observer/index.stories.tsx
  tsconfig.json
Labels: enhancement

#281 InputElement class
  src/components/BooleanInput/index.ts
  src/components/Input/index.ts
  src/components/InputElement/index.ts
  src/components/InputElement/style.scss
  src/components/Label/index.ts
  src/components/NumericInput/component.tsx
  src/components/NumericInput/index.ts
  src/components/TextInput/index.ts
  src/components/index.ts
  src/scss/components.scss
Labels: enhancement

#283 Various typing improvements
  src/components/ColorPicker/index.ts
  src/components/Container/index.ts
  src/components/GridView/index.ts
  src/components/Label/index.ts
  src/components/NumericInput/index.ts
  src/components/SelectInput/index.ts
  src/components/TextInput/index.ts
  src/components/TreeView/index.ts
Labels: enhancement

#285 Further type refinements
  src/binding/BindingBase/index.ts
  src/binding/BindingObserversToElement/index.ts
  src/binding/BindingTwoWay/index.ts
  src/components/Container/index.ts
  src/components/Element/index.ts
  src/components/InputElement/index.ts
  src/components/MenuItem/index.ts
  src/components/SelectInput/index.ts
Labels: enhancement

#286 Add Icon Browser
  examples/elements/arrayinput.html
  examples/elements/booleaninput.html
  examples/elements/button.html
  examples/elements/canvas.html
  examples/elements/code.html
  examples/elements/colorpicker.html
  examples/elements/divider.html
  examples/elements/gradientpicker.html
  examples/elements/gridview.html
  examples/elements/infobox.html
  examples/elements/label.html
  examples/elements/labelgroup.html
  examples/elements/menu.html
  examples/elements/numericinput.html
  examples/elements/overlay.html
  examples/elements/panel.html
  examples/elements/progress.html
  examples/elements/radiobutton.html
  examples/elements/selectinput.html
  examples/elements/sliderinput.html
  examples/elements/spinner.html
  examples/elements/textareainput.html
  examples/elements/textinput.html
  examples/elements/treeview.html
  examples/elements/vectorinput.html
  examples/index.html
  examples/utilities/icon-browser.html
Labels: enhancement

#287 Remove `_treeOrder` member from `TreeViewItem`
  src/components/TreeView/index.ts
  src/components/TreeViewItem/index.ts
Labels: enhancement

#288 Minor binding refactor
  src/binding/BindingBase/index.ts
  src/binding/BindingElementToObservers/index.ts
  src/binding/BindingObserversToElement/index.ts
  src/binding/BindingTwoWay/index.ts
  src/components/Canvas/index.ts
  src/components/GridView/index.ts
Labels: enhancement

#289 Remove 7 unused NPM dependencies
  package-lock.json
  package.json
Labels: enhancement

#290 Switch build process to the official Rollup TypeScript plugin
  package-lock.json
  package.json
  rollup.config.mjs
Labels: enhancement

#292 Prohibit empty interfaces in the codebase
  package.json
  src/components/Divider/component.tsx
  src/components/Divider/index.ts
  src/components/index.ts
Labels: enhancement

#293 Binding observer fix
  src/binding/BindingElementToObservers/index.ts
Labels: bug

#294 VectorInput step fix
  src/components/VectorInput/index.ts
Labels: bug

#295 Fix 9 more `@ts-ignore` statements
  src/components/ArrayInput/index.ts
  src/components/GradientPicker/index.ts
  src/components/SliderInput/index.ts
  src/components/TreeView/index.ts
Labels: enhancement

#296 React class prop fix
  src/components/Element/component.tsx
Labels: bug

#298 Panel component onClickRemove function
  src/components/Panel/index.ts
Labels: bug

#300 Enable build of docs site on Windows
  docs/README.md
  package-lock.json
  package.json
Labels: enhancement

#297 Minor refactor of `ColorPicker`
  src/components/ColorPicker/index.ts
Labels: enhancement

#302 Refactor element registry
  src/components/Element/index.ts
Labels: enhancement

#301 Refactor accessing of childNodes array
  react/tsconfig.json
  src/components/Menu/index.ts
  src/components/MenuItem/index.ts
  src/components/TreeView/index.ts
  src/components/TreeViewItem/index.ts
  tsconfig.json
Labels: enhancement
